spring.application.name=backend
# Configuração do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/teste
spring.datasource.username=teste
spring.datasource.password=teste

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# O Flyway cuidará das migrações automaticamente
spring.flyway.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
info.app.name=Mini-ERP Backend
info.app.version=1.0.0